name: Sync Fork

on:
  schedule:
    - cron: '*/7 * * * *' # every hour
  workflow_dispatch: # on button click

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v1.9
        with:
          owner: ${{ github.repository_owner }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          personal_token: ${{ secrets.GH_PERSONAL_TOKEN }}
          head: master
          base: master
          merge_method: merge
          pr_title: Fork Sync
          auto_approve: true
